#!/usr/bin/env ruby
%w(
  .
  vendor/junebug/lib
  vendor/daemons/lib
).reverse.each { |dir| $:.unshift(File.dirname(__FILE__) + "/" + dir) }

require 'daemons'
require 'fileutils'
require 'junebug/config'

JUNEBUG_ROOT = ENV['JUNEBUG_ROOT'] = File.dirname(File.expand_path(__FILE__))

Daemons.run(Junebug::Config.script, :dir_mode=>:normal, :dir=>JUNEBUG_ROOT)

